sudo: required

services:
  - docker

script:
  - docker run --rm -v "$(pwd)":/work -w /work sasah/maven mvn clean package
  - docker build --no-cache --pull -t sasah/tol3:latest .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push sasah/tol3:latest
